name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: git lfs install

      - name: Login to Hugging Face
        uses: HuggingFaceH4/huggingface-login@v1
        with:
          hf_token: ${{ secrets.HF_TOKEN }}

      - name: Configure git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"

      - name: Add HF remote and push
        env:
          HF_REPO: yourname/your-repo   # <-- put YOUR repo-id here
        run: |
          git remote add hf https://huggingface.co/${HF_REPO}.git || true
          git push hf HEAD:main
