name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: git lfs install

      - name: Configure git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"

      - name: Push to Hugging Face (no external action)
        env:
          HF_REPO: sravyakakumani04/pyannote       # <-- change to YOUR repo id
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # <-- add this secret in repo Settings
        run: |
          git remote add hf https://oauth2:${HF_TOKEN}@huggingface.co/${HF_REPO}.git || true
          git push hf HEAD:main
